# Keyvault - the missing Azure Keyvault package for Go

## BIG NOTE

This is not the official Go SDK Keyvault, as such, is not officially supported by Microsoft. It does not use any of the Keyvault SDK code.

Please keep this in mind.

## Introduction

One of the most needed services in cloud development is a safe place to securely store secrets and certificates. In Azure that is Keyvault.

The Azure SDK for Go has an official Keyvault package. Like much of the SDK, a lot of it is autogenerated from REST, which does not yield a nice API surface.

The Go SDK suffers from a few problems:
- Does not support Go types such as time.Time, x509.Certificate, tls.Certificate, ...
- Certificate use require deep dives into Kevault Documenation to access
- Documentation is quite long and hard to look through
- Non-Idomatic

My team wanted something that did what 99% of Go users would want without spending time diving into documenation.

We currently support:
- Secret operations
- Certificate operations
- TLS specific operations

Not all operations are supported in the high level API, as many of them are mostly useful to Microsoft teams creating tooling. Most of those are available through a lower level API.

## Usage

### Creating a client

### Accessing a sub-client

### Fetch a secret

### Fetch a TLS cetificate

### Access lower level API
